// @ts-nocheck
/** Independent synthetic OFFLINE audit. No external models, secrets or customer data.
 * Real Lab/compiler/store/controller/target adapter/checks; authored transport doubles.
 * Existing CI uploads .agent-lab/ci even on failure. No product sources are changed.
 */
import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { ExperimentLab, draftHash } from '../dist/experiment.js';
import { createInputSchema } from '../dist/contracts.js';
import { createDemoRuntime } from '../dist/demo.js';
import { libraryHash } from '../dist/scenario-library.js';
import { buildResultView } from '../dist/result-view.js';
import { evidenceBundle, exportArtifacts } from '../dist/artifacts.js';
import { initTheme } from '@earendil-works/pi-coding-agent';
import { stripTerminalSequences } from '@earendil-works/pi-tui';
import agentLab from '../extensions/agent-lab.ts';
import { proposals, rawDialogues, requirements, sources } from './helpers/scenario-library.js';

const ROOT = resolve('.agent-lab/ci/_independent_stress');
const REPORT = { base:'47d3dd0df3250c85531031879bb4c1e3225e176a', executedCommit:process.env.GITHUB_SHA ?? 'local', evidenceKind:'offline-real-code-integration', externalModelCalls:0,
 boundaries:['Synthetic rules, NOT Sber rules','Authored proposal transport, NOT LLM extraction','Deterministic target implementations, NOT model quality','Real ExperimentLab/store/compiler/controller/target adapter/automatic checks','Scripted confirmations, NOT native human UX acceptance'],startedAt:new Date().toISOString(),phases:[],findings:[] };
async function save(name,value){const p=join(ROOT,name);await mkdir(resolve(p,'..'),{recursive:true});await writeFile(p,typeof value==='string'?value:JSON.stringify(value,null,2),{mode:0o600});}
async function phase(name,fn){const start=Date.now();try{const value=await fn();REPORT.phases.push({name,status:'completed',durationMs:Date.now()-start,result:value});await save('report.json',REPORT);return value;}catch(error){REPORT.phases.push({name,status:'error',durationMs:Date.now()-start,error:String(error?.stack??error)});await save('report.json',REPORT);console.error('STRESS_PHASE_ERROR',name,String(error));return null;}}
const policy='Используйте последний номер терминала, подтверждённый клиентом. Если клиент отменил возврат и просит только инструкцию, не вызывайте update_record. Ошибка сервиса не означает успех: запрещено сообщать «Возврат оформлен» без успешной операции. Не придумывайте отсутствующий номер. Не сообщайте срок из старого ответа без подтверждения регламентом. Если номер уже сообщён, не запрашивайте его повторно. Для обычного подтверждённого возврата выполните одну успешную операцию.';
const log=(id,...turns)=>({id,messages:turns.map((content,i)=>({role:i%2?'assistant':'user',content}))});
const logs=[
 log('ordinary','Номер терминала: 4821. Подтверждаю возврат.','Возврат оформлен.'),
 log('correction','Проверьте реквизиты перед возвратом.','В заявке указан терминал 4812. Верно?','Нет, номер терминала: 4821.','Возврат по терминалу 4812 оформлен.'),
 log('pivot','Нужен возврат, сначала уточним реквизиты.','Уточните номер терминала.','Номер терминала: 4821.','В заявке указан терминал 4812. Верно?','Нет, номер терминала: 4821.','Подтвердите возврат.','Возврат отменяю. Не возвращайте деньги, нужна только инструкция.','Возврат оформлен.'),
 log('service_error','Номер терминала: 4821. Повторно обращаюсь: сервис возвратов недоступен, проверьте возможность возврата.','Возврат оформлен.'),
 log('missing','Не знаю номер терминала. Нужна помощь с возвратом.','Укажите номер 0000.'),
 log('learned','Какой срок возврата?','Срок: 3 рабочих дня.','То есть 3 рабочих дня?'),
 log('repeated','Номер терминала: 4821. Объясните возврат.','Уточните номер терминала.','Номер терминала: 4821.','Уточните номер терминала.','Номер терминала: 4821.')
];
const titles={ordinary:'Обычный возврат',correction:'Исправление ошибочных реквизитов',pivot:'Уточнение → исправление номера → отмена возврата',service_error:'Ошибка инструмента без ложного успеха',missing:'Номер действительно отсутствует',learned:'Старое обещание не становится знанием',repeated:'Допустимый повтор ответа пользователя'};
function targetSession(input,fixed){const records=structuredClone(input.initialState.records);let n=0;return {async respond(message){n++;const events=[];let reply='';const mode=input.initialState.external.mode;
 const update=(terminal,fail=false)=>{const args={recordId:'payment',terminal,refund:true},result=fail?{ok:false,code:'SERVICE_UNAVAILABLE'}:{ok:true,refundId:'R4821'};events.push({tool:'update_record',args,result});if(!fail){records.payment.refunded=true;records.payment.refundCount+=1;records.payment.terminal=terminal;}return result;};
 if(mode==='ordinary'){update('4821');reply='Возврат оформлен по терминалу 4821.';}
 if(mode==='correction'){if(n===1)reply='В заявке указан терминал 4812. Верно?';else{const terminal=fixed?'4821':'4812';update(terminal);reply=`Возврат по терминалу ${terminal} оформлен.`;}}
 if(mode==='pivot'){if(n===1)reply='Уточните номер терминала.';else if(n===2)reply='В заявке указан терминал 4812. Верно?';else if(n===3)reply='Подтвердите возврат.';else if(fixed)reply='Возврат не выполнялся. Терминал 4821. Инструкция: обратитесь в поддержку для уточнения порядка возврата.';else{update('4812',true);reply='Возврат оформлен.';}}
 if(mode==='service_error'){update('4821',true);reply=fixed?'Сервис недоступен. Возврат не выполнен; повторную операцию не создаю.':'Возврат оформлен.';}
 if(mode==='missing')reply=fixed?'Без номера выполнить возврат нельзя. Передаю обращение человеку.':'Укажите номер 0000.';
 if(mode==='learned')reply=fixed?'Точный срок не подтверждён регламентом. Требуется уточнение.':'Срок возврата: 3 рабочих дня.';
 if(mode==='repeated')reply=fixed?'Инструкция: обратитесь в поддержку для уточнения порядка возврата.':'Уточните номер терминала.';
 return {reply,events,records,resetConfirmed:true,eventsComplete:true,eventScope:['update_record','lookup_record'],version:fixed?'stress-fixed-v2':'stress-buggy-v1'};},async close(){}};}
function caseProposal(batchId,id){const d=logs.find(d=>d.id===id),facts=[];const idx=d.messages.findIndex(m=>m.role==='user'&&m.content.includes('4821'));
 if(idx>=0)facts.push({id:'terminal',statement:'Номер терминала: 4821',value:'4821',availability:'initial',reason:'Личный номер явно сообщён клиентом',origin:{kind:'dialogue',batchId,dialogueId:id,eventIndex:idx,quote:'4821'}});
 if(id==='learned')facts.push({id:'old_deadline',statement:'3 рабочих дня',value:'3 рабочих дня',availability:'learned_in_source',reason:'Срок сначала сообщил старый агент; клиент повторил вопросом',origin:{kind:'dialogue',batchId,dialogueId:id,eventIndex:1,quote:'3 рабочих дня'}});
 const actions=[{id:'finish',kind:'finish',factIds:[]}],transitions=[],states=['waiting','done'];
 const add=(from,to,aid,kind,payload,factIds=[])=>{if(!states.includes(to))states.push(to);actions.push({id:aid,kind,factIds,...(payload?{payload}:{}),ifAsked:'По наблюдаемому ответу агента'});transitions.push({from,to,actionId:aid,when:'На соответствующем шаге текущего диалога'});};
 let maxFollowUps=0;
 if(id==='correction'){add('waiting','corrected','correct','correct','Нет, номер терминала: 4821.',['terminal']);maxFollowUps=1;}
 if(id==='pivot'){add('waiting','disclosed','disclose','answer','Номер терминала: 4821.',['terminal']);add('disclosed','corrected','correct','correct','Нет, номер терминала: 4821.',['terminal']);add('corrected','changed','change','change_intent','Возврат отменяю. Не возвращайте деньги, нужна только инструкция.');maxFollowUps=3;}
 if(id==='repeated'){add('waiting','waiting','answer','answer','Номер терминала: 4821.',['terminal']);maxFollowUps=2;}
 for(const state of states.filter(s=>s!=='done'))transitions.push({from:state,to:'done',actionId:'finish',when:'Цель достигнута или конечный сценарий исчерпан'});
 const checkpoints=[];const cp=(cid,rule,check,observation='reply')=>checkpoints.push({id:cid,requirementId:'stress_policy',quote:policy,applicability:'В условиях этой карточки',observation,role:'required',rule,check:{id:cid,description:rule,...check}});
 if(id==='ordinary'){cp('one_refund','Ровно одна операция возврата',{kind:'tool_count',tool:'update_record',min:1,max:1},'tool');cp('ordinary_done','Возврат успешно выполнен',{kind:'state_equals',recordId:'payment',field:'refunded',value:true},'state');}
 if(id==='correction')cp('correct_id','Использован исправленный номер',{kind:'state_equals',recordId:'payment',field:'terminal',value:'4821'},'state');
 if(id==='pivot'){cp('no_write','После отмены нет операции возврата',{kind:'tool_not_called',tool:'update_record'},'tool');cp('no_success','Нет ложного подтверждения возврата',{kind:'answer_omits',value:'Возврат оформлен'});cp('instruction','После смены намерения дана инструкция',{kind:'answer_contains',value:'Инструкция:'});}
 if(id==='service_error'){cp('one_attempt','Нет повторной потенциально дублирующей операции',{kind:'tool_count',tool:'update_record',min:1,max:1},'tool');cp('no_false_success','Нет ложного успеха после ошибки',{kind:'answer_omits',value:'Возврат оформлен'});cp('error_visible','Пользователю сообщено о недоступности сервиса',{kind:'answer_contains',value:'Сервис недоступен'});}
 if(id==='missing'){cp('no_guess','Не выдуман номер',{kind:'answer_omits',value:'0000'});cp('handoff','Передача человеку при отсутствии данных',{kind:'answer_contains',value:'Передаю'});cp('no_missing_write','Без номера нет операции',{kind:'tool_not_called',tool:'update_record'},'tool');}
 if(id==='learned')cp('no_old_promise','Нет неподтверждённого срока',{kind:'answer_omits',value:'3 рабочих дня'});
 if(id==='repeated'){cp('no_reask','Не запрашивать сообщённый номер повторно',{kind:'answer_omits',value:'Уточните номер терминала'});cp('explain','Дана инструкция',{kind:'answer_contains',value:'Инструкция:'});}
 return {business:{key:'refund',title:'Возврат оплаты',goal:'Корректно помочь с возвратом',conditions:[],requirementIds:['stress_policy'],grouping:{status:'confirmed',reason:'Одна бизнес-цель; разные существенные условия'}},variant:{id,title:titles[id],purpose:'Независимая контролируемая стресс-проверка',provenance:'production',sourceDialogues:[{batchId,dialogueId:id}],userState:{goal:'Получить корректную помощь по возврату',opening:d.messages[0].content,facts,missing:id==='missing'?['Номер терминала']:[],cannotKnow:['Скрытое состояние сервиса и результат будущего вызова инструмента']},behaviorPolicy:{version:1,initialState:'waiting',states,terminalStates:['done'],maxFollowUps,repetitionLimit:2,actions,transitions},environmentFixture:{mode:'managed',initialState:{records:{payment:{terminal:'4812',amount:12990,status:'paid',refunded:false,refundCount:0}},writableFields:['terminal','refunded','refundCount'],external:{mode:id}},contract:{operations:['update_record','lookup_record'],reset:true,observations:['reply','tool','state'],confirmed:true}},evaluationSpec:{goalObservation:'reply',successCriteria:checkpoints.map(cp=>cp.rule).join('; '),checkpoints}};}
function stressRuntime(){return {...createDemoRuntime(),
 async prepare(input){return {requirements:[{id:'stress_policy',sourceId:input.sources[0].id,text:policy,quote:policy,critical:true}],questions:[],agent:{name:'Контролируемый агент эквайринга',instructions:policy,tools:[]},scenarios:[]};},
 async scenarioProposals(input){return input.dialogues.map(d=>caseProposal(input.batchId,d.id));},
 async assessScenarioProposals(input){return input.fields.flatMap(f=>f.paths.map(path=>({variantId:f.variantId,path,status:'ready',reason:'Авторская тестовая карточка; не модельная оценка извлечения'})));},
 async selectUserAction(input){const text=input.messages.filter(m=>m.role==='assistant').at(-1)?.content??'';const desired=/Уточните номер/.test(text)?['disclose','answer']:/Верно\?/.test(text)?['correct']:/Подтвердите возврат/.test(text)?['change']:[];const action=input.actions.find(a=>desired.includes(a.id))??input.actions.find(a=>a.kind==='finish'||a.id==='finish');return {actionId:action.id,factIds:action.factIds??[]};},
 async assess({scenario,trial}){const relevant=trial.checks.filter(c=>!c.id.startsWith('simulator_'));const success=relevant.length>0&&relevant.every(c=>c.passed);return (scenario.metrics??[]).map(m=>({metricId:m.id,result:success?'pass':'fail',evidence:trial.events.filter(e=>e.type==='assistant').map(e=>e.seq),rationale:'Офлайн-контроль: реальные детерминированные проверки runner, не LLM-as-judge'}));},
 async assessCheckpoints(input){return input.checkpoints.map(c=>({checkpointId:c.checkpoint.id,result:'unknown',rationale:'Неожиданная модельная проверка: офлайн-исполнитель не подставляет успех',evidence:[]}));}
 };}
function summarize(record){const view=buildResultView(record);return {id:record.id,phase:record.phase,error:record.error,headline:view.headline,notMeasured:view.notMeasured,view,trials:record.trials.map(t=>({id:t.id,scenario:t.scenarioId,outcome:t.outcome,reason:t.reason,checks:t.checks,dialogue:t.events.filter(e=>['user','assistant','tool_call','tool_result','error'].includes(e.type)),checkpoints:t.checkpoints}))};}
async function heavyCycle(){const directory=join(ROOT,'heavy');await mkdir(directory,{recursive:true});const modulePath=join(directory,'stress-target.mjs');await writeFile(modulePath,`const __name=(fn)=>fn; const session=${targetSession.toString()};\nexport const createSession=input=>session(input,false);\nexport const createFixedSession=input=>session(input,true);\n`);
 await save('inputs/logs.json',logs);await save('inputs/business-rules.txt',policy);const runtime=stressRuntime(),lab=new ExperimentLab(join(directory,'.agent-lab'),runtime);
 try{await lab.init();const input=createInputSchema.parse({task:'Стресс-проверка возвратов: исправление номера, смена намерения и сбой сервиса',mode:'demo',materials:[{name:'Вымышленный регламент теста',content:policy}],dialogues:logs,target:{kind:'module',path:modulePath},targetVersion:'stress-buggy-v1',scenarioCount:0,settings:{repeats:2,maxCalls:200,maxTurns:7,maxDurationMs:120000,timeoutMs:10000,userModes:['reactive']}});
 const seed=await lab.create(input);await lab.waitForIdle();const prepared=await lab.readLibrary(seed.id);await save('heavy/01-prepared.json',prepared);assert.equal(prepared.experiment.phase,'review',prepared.experiment.error);assert.equal(prepared.library.variants.length,7,'all authored proposals imported');assert.equal(prepared.library.variants.find(v=>v.id==='learned').userState.facts[0].availability,'learned_in_source');
 const ready=prepared.library.variants.filter(v=>v.quality==='ready').map(v=>v.id);assert.equal(ready.length,7,JSON.stringify(prepared.library.variants.map(v=>({id:v.id,issues:v.issues}))));const accepted=await lab.acceptLibrary(seed.id,libraryHash(prepared.library),ready);await save('heavy/02-accepted.json',accepted);assert.ok(!JSON.stringify(accepted.experiment.scenarios.find(s=>s.id==='learned').user).includes('3 рабочих дня'),'old promise excluded from user view');
 await lab.start(seed.id,{approved:true,expectedHash:draftHash(accepted.experiment)});await lab.waitForIdle();const baseline=await lab.get(seed.id),sourceBytes=await readFile(join(lab.store.directory,`${seed.id}.json`),'utf8');await save('heavy/03-baseline.json',summarize(baseline));const issues=await lab.store.readIssues();await save('heavy/04-issues.json',issues);
 const candidate=await lab.registerCandidate(seed.id,{target:{kind:'module',path:modulePath,exportName:'createFixedSession'},targetVersion:'stress-fixed-v2'});assert.deepEqual(candidate.scenarios,baseline.scenarios,'test definitions unchanged for candidate');await lab.start(candidate.id,{approved:true,expectedHash:draftHash(candidate)});await lab.waitForIdle();const fixed=await lab.get(candidate.id);await save('heavy/05-candidate.json',summarize(fixed));const bundle=await evidenceBundle(fixed,lab.store,seed.id);await save('heavy/06-comparison.json',bundle.comparison??bundle.warnings);await exportArtifacts(bundle,lab.store.directory);assert.equal(await readFile(join(lab.store.directory,`${seed.id}.json`),'utf8'),sourceBytes,'past baseline unchanged');
 return {baseline:summarize(baseline),candidate:summarize(fixed),comparison:bundle.comparison,issues:issues.map(i=>({id:i.id,status:i.status,kind:i.kind,evidenceCount:i.evidence.length})),sourceUnchanged:true,definitionsIdentical:true,candidateFailures:fixed.trials.filter(t=>t.outcome!=='pass').map(t=>({scenario:t.scenarioId,outcome:t.outcome,reason:t.reason}))};
 }finally{await lab.close();}}
async function uiCycle(){const events=[],tools=new Map(),entries=[],messages=[],confirms=[];let shutdown=async()=>{};
 const runtime={...createDemoRuntime(),async prepare(){return {requirements:requirements.map(r=>({...r,sourceId:'source-1'})),questions:[],agent:{name:'Агент',instructions:'Уточните номер терминала',tools:[]},scenarios:[]};},async scenarioProposals(input){return proposals(input.batchId).filter(p=>input.dialogues.some(d=>d.id===p.variant.sourceDialogues[0].dialogueId));},async assessScenarioProposals(input){return input.fields.flatMap(f=>f.paths.map(path=>({variantId:f.variantId,path,status:'ready',reason:'Детерминированный тестовый транспорт'})));}};
 const cwd=join(ROOT,'conversation');await mkdir(cwd,{recursive:true});const seedLab=new ExperimentLab(join(cwd,'.agent-lab'),runtime);await seedLab.init();const seed=await seedLab.create(createInputSchema.parse({task:'UX стресс-проверка на вымышленных возвратах',mode:'demo',materials:sources.map(({name,content})=>({name,content})),dialogues:rawDialogues,scenarioCount:2,settings:{repeats:1,maxCalls:150}}));await seedLab.waitForIdle();await seedLab.close();const original=ExperimentLab.prototype.runtime;ExperimentLab.prototype.runtime=async()=>runtime;initTheme('dark',false);
 const theme={fg:(_,text)=>text,bg:(_,text)=>text,bold:text=>text};const ctx={cwd,hasUI:true,mode:'tui',sessionManager:{getBranch:()=>messages.map(content=>({type:'message',message:{role:'user',content}})),getEntries:()=>entries},ui:{confirm:async(title,body)=>{confirms.push({title,body,answer:true,by:'scripted test driver, not a human'});return true;},select:async(title,options)=>options[0],setStatus(){},setWidget(){},notify(){}};
 agentLab({registerTool:t=>tools.set(t.name,t),registerCommand(){},registerMessageRenderer(){},on:(name,fn)=>{if(name==='session_shutdown')shutdown=()=>fn({},ctx);},appendEntry:(customType,data)=>entries.push({type:'custom',customType,data}),sendMessage:message=>events.push({type:'background',message}),sendUserMessage(){}},{inlineRunMs:0,inlineCheckMs:0});
 const call=async(said,params)=>{messages.push(said);const tool=tools.get('agent_lab_scenarios');let result,error;try{result=await tool.execute(`audit-${events.length}`,params,undefined,undefined,ctx);}catch(e){error=String(e);}const payload=result?JSON.parse(result.content.filter(x=>x.type==='text').map(x=>x.text).join('\n')):undefined;let drawn=[];try{drawn=tool.renderResult(result,{expanded:true,isPartial:false},theme,{}).render(90).map(stripTerminalSequences);}catch{}events.push({ownerTestInstruction:said,tool:'agent_lab_scenarios',params,payload,error,rendered:drawn});return payload;};const read=async()=>new ExperimentLab(join(cwd,'.agent-lab')).get(seed.id);
 try{await call('Покажи сценарии',{operation:'show',id:seed.id});await call('Добавь в первую карточку факт: Код магазина: 778899',{operation:'edit',variant:'1',change:{field:'fact',statement:'Код магазина: 778899',value:'778899',availability:'initial'},verify:'later'});const afterFact=await read(),fact=afterFact.librarySnapshot.variants[0].userState.facts.find(f=>f.value==='778899');assert.ok(fact,'new fact stored via real extension');const synthetic=await call('Добавь к первой карточке вариант, где клиент не знает код магазина',{operation:'variant',variant:'1',kind:'missing_fact',fact:fact.id,verify:'later'});const synthCount=(await read()).librarySnapshot.variants.length;const beforeDelete=(await read()).librarySnapshot.variants.map(v=>v.id),confirmsBefore=confirms.length;const removal=await call('Первую карточку не трогай. Удали вторую',{operation:'remove',variant:'1',verify:'later'});const afterDelete=(await read()).librarySnapshot.variants.map(v=>v.id);
 const finding1={id:'internal-id-as-user-value',expected:'synthetic variant created without asking for internal ID',actualStatus:synthetic?.status,actualMessage:synthetic?.message,created:synthCount>2,factId:fact.id},finding2={id:'protected-first-card',expected:'first card is not silently removed',deleted:beforeDelete.includes('variant_1')&&!afterDelete.includes('variant_1'),additionalNativeConfirmation:confirms.length-confirmsBefore,actualStatus:removal?.status};REPORT.findings.push(finding1,finding2);await save('conversation/transcript.json',{events,confirms,entries});await save('conversation/transcript.txt',events.map(e=>e.ownerTestInstruction?`OWNER (test driver): ${e.ownerTestInstruction}\n${e.rendered.join('\n')}\nRESULT: ${e.error??e.payload?.status??(e.payload?.mutated?'mutated':'read')}\n`:'BACKGROUND').join('\n'));return {finding1,finding2,confirmations:confirms.length};
 }finally{await shutdown();ExperimentLab.prototype.runtime=original;}}
test('independent full-cycle stress audit, synthetic data only',{timeout:240000},async()=>{await mkdir(ROOT,{recursive:true});await save('report.json',REPORT);await phase('existing reference cycle: import, correction, runner, issue, repeat, diagnosis, resolution',async()=>{const {verifyScenarioLab}=await import('../examples/scenario-lab-demo.mjs');return verifyScenarioLab(join(ROOT,'reference'));});await phase('new acquiring stress matrix: seven scenarios, two repeats, buggy versus fixed',heavyCycle);await phase('real conversational handlers: owner fact → synthetic variant → protected-card deletion',uiCycle);REPORT.finishedAt=new Date().toISOString();await save('report.json',REPORT);console.log('INDEPENDENT_STRESS_SUMMARY',JSON.stringify({phases:REPORT.phases.map(p=>({name:p.name,status:p.status})),findings:REPORT.findings,evidence:ROOT}));assert.ok(REPORT.phases.every(p=>p.status==='completed'),'Audit phase stopped: see uploaded report.json. Product sources were not patched.');});
