import assert from 'node:assert/strict';
import { createCipheriv,createDecipheriv,randomBytes } from 'node:crypto';
import { sealPreparedRun,openPreparedRun,FROZEN_SLOT,FROZEN_TARGET_PREFIX } from '../langwatch-custom/src/server/scenarios/execution/frozen-run-contract.ts';
const key=randomBytes(32);
const encrypt=(text:string)=>{const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',key,iv);const value=Buffer.concat([cipher.update(text,'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),value]).toString('base64');};
const decrypt=(text:string)=>{const b=Buffer.from(text,'base64');const cipher=createDecipheriv('aes-256-gcm',key,b.subarray(0,12));cipher.setAuthTag(b.subarray(12,28));return Buffer.concat([cipher.update(b.subarray(28)),cipher.final()]).toString('utf8');};
const command={tenantId:'project',scenarioId:'case',scenarioRunId:'run',batchRunId:'batch',scenarioSetId:'suite',target:{type:'http',referenceId:'agent'},metadata:{langwatch:{scenarioVersion:1}}};
const prepared={success:true as const,data:{scenario:{id:'case',version:1,situation:'Original world',criteria:['Original criterion'],labels:[]},parameters:{known:'fixture'},adapterData:{url:'http://fixture',headers:{authorization:'secret-header'}},simulatorModelParams:{model:'simulator',api_key:'secret-model-key'},judgeModelParams:{model:'judge',temperature:0,api_key:'secret-model-key'}},telemetry:{endpoint:'http://localhost',apiKey:'secret-project-key'}};
const queued=sealPreparedRun(command,prepared,encrypt,'sdk-one');
const job={projectId:'project',scenarioId:'case',scenarioRunId:'run',batchRunId:'batch',setId:'suite',target:queued.target,secretParameters:queued.secretParameters};
prepared.data.scenario.criteria[0]='Edited while queued';prepared.data.judgeModelParams.model='changed judge';prepared.data.adapterData.url='http://changed-target';
const restored=openPreparedRun(job,decrypt,'sdk-one')!;
assert.deepEqual(restored.data.scenario.criteria,['Original criterion']);assert.equal(restored.data.judgeModelParams.model,'judge');assert.equal(restored.data.adapterData.url,'http://fixture');
assert.deepEqual(openPreparedRun(job,decrypt,'sdk-one'),restored,'Retry must restore the same conditions');
assert(!JSON.stringify(queued.metadata).includes('secret-'),'No credentials in public receipt');
assert.throws(()=>openPreparedRun({...job,projectId:'other-project'},decrypt,'sdk-one'),/identity/);
assert.throws(()=>openPreparedRun(job,decrypt,'sdk-two'),/SDK changed/);
assert.throws(()=>openPreparedRun({...job,secretParameters:{}},decrypt,'sdk-one'),/missing/);
assert(queued.target.referenceId.startsWith(FROZEN_TARGET_PREFIX),'An old worker cannot resolve the live target');
assert.equal(openPreparedRun({...job,target:command.target,secretParameters:{}},decrypt,'sdk-one'),null,'Old runs remain readable');
assert.throws(()=>openPreparedRun({...job,secretParameters:{[FROZEN_SLOT]:'damaged'}},decrypt,'sdk-one'));
console.log('PASS: scenario/model/target drift, retry, credential privacy, tenant binding, SDK drift, missing/corrupt snapshot, legacy compatibility');
