import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {criterionKey,evaluateRequiredCriteria,measurementOutcome} from '../langwatch-custom/src/server/scenarios/execution/measurement-outcome.ts';
const sdk=fs.readFileSync('langwatch/.local/app/platform/app/node_modules/@langwatch/scenario/dist/index.js','utf8');
const at=sdk.indexOf('var criterionToParamName =');const end=sdk.indexOf('// src/agents/judge/judge-agent.ts',at);
const context:any={__nativeMeasurement:{criterionKey,evaluateRequiredCriteria}};vm.createContext(context);vm.runInContext(sdk.slice(at,end)+'\nthis.key=criterionToParamName;',context);
const russian=['Агент должен ответить клиенту понятной инструкцией без перенаправления в другую службу поддержки.','Агент не должен передавать клиенту служебные данные или внутренние сведения банковской системы.'];
const before=russian.map((c,i)=>context.key(c,i));
if(before[0]===before[1])console.log('CONFIRMED upstream: two Cyrillic criteria collapse into one tool property');
const keys=russian.map(criterionKey);assert.equal(new Set(keys).size,2);
const result=evaluateRequiredCriteria(russian,{criterion_1:'false',criterion_0:'true'});
assert.deepEqual(result.metCriteria,[russian[0]]);assert.deepEqual(result.unmetCriteria,[russian[1]],'JSON insertion order cannot change attribution');
const twenty=Array.from({length:20},(_,i)=>'Check '+i);const incomplete=evaluateRequiredCriteria(twenty,{criterion_0:'true'});
assert.equal(incomplete.verdict,'inconclusive');assert.equal(incomplete.unmetCriteria.length,0);assert.equal(incomplete.inconclusiveCriteria.length,19);
assert.equal(measurementOutcome('FAILED',incomplete).acceptance,'not_verified');
assert.equal(measurementOutcome('ERROR',{verdict:'failure',unmetCriteria:['not executed'],error:'fixture unavailable'}).violations,0);
assert.equal(evaluateRequiredCriteria(['real violation'],{criterion_0:'false'}).verdict,'failure');
assert.equal(measurementOutcome('SUCCESS',{verdict:'success',metCriteria:['A'],inconclusiveCriteria:['B']}).acceptance,'not_verified');
console.log('PASS: independent Cyrillic checks, shuffled response keys, 1 PASS + 19 UNKNOWN, infrastructure error, real FAIL, incomplete-success gate');
