const assert=require('node:assert/strict');const path=require('node:path');const fs=require('node:fs');
const root=path.resolve(__dirname,'..'),app=path.join(root,'langwatch/.local/app/platform/app');
const esbuild=require(path.join(app,'node_modules/esbuild'));
const output=path.join(root,'langwatch/.local/evidence/native-csv-probe.cjs');fs.mkdirSync(path.dirname(output),{recursive:true});
esbuild.buildSync({entryPoints:[path.join(app,'src/server/export/scenario-runs/csv-serializer.ts')],bundle:true,platform:'node',format:'cjs',outfile:output,alias:{'~':path.join(app,'src')},logLevel:'silent'});
const serializer=require(output),parse=require(path.join(app,'node_modules/papaparse'));
const run={name:'Public fixture',status:'ERROR',timestamp:Date.now(),messages:[],results:{verdict:'inconclusive',metCriteria:['known'],unmetCriteria:[],inconclusiveCriteria:Array.from({length:19},(_,i)=>'unknown '+i)}};
const criteria=parse.parse(serializer.serializeRunsToCriteriaCsv({runs:[run],includeHeader:true}),{header:true}).data.filter(r=>r.criterion);
assert.equal(criteria.length,20);assert.equal(criteria.filter(r=>r.met==='UNKNOWN').length,19);assert.equal(criteria.filter(r=>r.met==='false').length,0);assert(criteria.every(r=>r.status_category==='unmeasured'));
const full=parse.parse(serializer.serializeRunsToFullCsv({runs:[run],includeHeader:true}),{header:true}).data[0];assert.equal(full.run_inconclusive_criteria_count,'19');assert.equal(JSON.parse(full.run_inconclusive_criteria).length,19);
console.log('PASS actual native CSV serializer: 1 PASS + 19 UNKNOWN preserved in both export modes');
const summaryOutput=path.join(root,'langwatch/.local/evidence/native-summary-probe.cjs');
esbuild.buildSync({entryPoints:[path.join(app,'src/components/suites/run-history-transforms.ts')],bundle:true,platform:'node',format:'cjs',outfile:summaryOutput,alias:{'~':path.join(app,'src')},logLevel:'silent'});
const history=require(summaryOutput),summary=history.computeGroupSummary({group:{scenarioRuns:[{...run,durationInMs:0}]}});
assert.equal(summary.passRate,null);assert.equal(summary.failedCount,0);assert.equal(summary.unmeasuredCount,1);assert.equal(history.worstStatus(summary),'ERROR');
console.log('PASS actual native summary: all-UNKNOWN group has no quality percentage or green SUCCESS');
