import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const app=new URL('../langwatch/.local/app/platform/app/',import.meta.url);
const require=createRequire(new URL('package.json',app));
const esbuild=require('esbuild');
const source=fs.readFileSync(new URL('src/server/scenarios/execution/data-prefetcher.ts',app),'utf8');
const begin=source.indexOf('async function fetchScenario({');const end=source.indexOf('type FetchProjectResult',begin);
assert(begin>=0&&end>begin);
const code=esbuild.transformSync(source.slice(begin,end)+'\nglobalThis.probe=fetchScenario;',{loader:'ts',format:'cjs'}).code;
const context={parseScenarioParameterDefinitions:()=>[],partitionParameterDefinitions:()=>({plain:[],secret:[]}),withoutParameterNames:({values})=>values,mergeRunParameters:()=>({}),renderScenarioContent:async({situation,criteria})=>({ok:true,situation,criteria})};
vm.createContext(context);vm.runInContext(code,context);
let criteria=['before queue delay'];const fetcher={getById:async()=>({id:'case',version:1,name:'Fixture',situation:'Synthetic world',criteria,labels:[]})};
const before=await context.probe({projectId:'fixture',scenarioId:'case',fetcher});
criteria=['edited before worker'];const after=await context.probe({projectId:'fixture',scenarioId:'case',fetcher});
assert.equal(before.config.criteria[0],'before queue delay');assert.equal(after.config.criteria[0],'edited before worker');
console.log('CONFIRMED: actual installed fetchScenario reads the live criterion; the queue snapshot must prevent this second read for new runs.');
