/*
 * A pull tokenizer over the XML grammar that office parts use: elements with attributes, character data,
 * CDATA, comments and processing instructions. A document type declaration is refused, so no entity can
 * expand; names keep their namespace prefix (`localName` drops it) because office parts are read by the
 * local names of a known vocabulary. The parts are generated by programs: broken markup means a damaged
 * file, never something to repair or guess around.
 */

export type XmlToken =
  | { kind: 'open'; name: string; attributes: ReadonlyMap<string, string>; empty: boolean }
  | { kind: 'close'; name: string }
  | { kind: 'text'; text: string };

const damaged = (what: string) => new Error(`Таблица повреждена: ${what}. Сохраните файл заново.`);
const isSpace = (char: string | undefined) => char === ' ' || char === '\t' || char === '\n' || char === '\r';

/** The name without its namespace prefix: `x:row` → `row`. */
export const localName = (name: string): string => name.slice(name.indexOf(':') + 1);

/** The tokens of `xml` in document order. Whitespace between elements comes out as text; readers skip what they do not collect. */
export function* xmlTokens(xml: string): Generator<XmlToken> {
  let at = xml.charCodeAt(0) === 0xfeff ? 1 : 0;
  while (at < xml.length) {
    const open = xml.indexOf('<', at);
    if (open === -1) { yield { kind: 'text', text: decodeEntities(xml.slice(at)) }; return; }
    if (open > at) yield { kind: 'text', text: decodeEntities(xml.slice(at, open)) };
    if (xml.startsWith('<!--', open)) { at = after(xml, '-->', open + 4, 'не закрыт комментарий'); continue; }
    if (xml.startsWith('<![CDATA[', open)) {
      const end = xml.indexOf(']]>', open + 9);
      if (end === -1) throw damaged('не закрыт блок CDATA');
      yield { kind: 'text', text: xml.slice(open + 9, end) };
      at = end + 3; continue;
    }
    if (xml.startsWith('<?', open)) { at = after(xml, '?>', open + 2, 'не закрыта инструкция обработки'); continue; }
    if (xml.startsWith('<!', open)) throw new Error('Таблица содержит объявление DTD — такие файлы Lab не читает. Сохраните таблицу заново в Excel.');
    if (xml[open + 1] === '/') {
      const end = xml.indexOf('>', open + 2);
      if (end === -1) throw damaged('не закрыт тег');
      yield { kind: 'close', name: xml.slice(open + 2, end).trim() };
      at = end + 1; continue;
    }
    const tag = openTag(xml, open + 1);
    yield tag.token;
    at = tag.end;
  }
}

function after(xml: string, marker: string, from: number, what: string): number {
  const end = xml.indexOf(marker, from);
  if (end === -1) throw damaged(what);
  return end + marker.length;
}

/** An opening tag from its name to `>` or `/>`; a `>` inside a quoted attribute value belongs to the value. */
function openTag(xml: string, start: number): { token: XmlToken; end: number } {
  let at = start;
  while (at < xml.length && !isSpace(xml[at]) && xml[at] !== '>' && xml[at] !== '/') at++;
  const name = xml.slice(start, at);
  if (!name) throw damaged('тег без имени');
  const attributes = new Map<string, string>();
  for (;;) {
    while (isSpace(xml[at])) at++;
    const char = xml[at];
    if (char === undefined) throw damaged('не закрыт тег');
    if (char === '>') return { token: { kind: 'open', name, attributes, empty: false }, end: at + 1 };
    if (char === '/') {
      if (xml[at + 1] !== '>') throw damaged('лишний знак «/» в теге');
      return { token: { kind: 'open', name, attributes, empty: true }, end: at + 2 };
    }
    const nameStart = at;
    while (at < xml.length && !isSpace(xml[at]) && xml[at] !== '=' && xml[at] !== '>' && xml[at] !== '/') at++;
    const attribute = xml.slice(nameStart, at);
    while (isSpace(xml[at])) at++;
    if (!attribute || xml[at] !== '=') throw damaged('атрибут без значения');
    at++;
    while (isSpace(xml[at])) at++;
    const quote = xml[at];
    if (quote !== '"' && quote !== '\'') throw damaged('значение атрибута без кавычек');
    const close = xml.indexOf(quote, at + 1);
    if (close === -1) throw damaged('не закрыта кавычка атрибута');
    attributes.set(attribute, decodeEntities(xml.slice(at + 1, close)));
    at = close + 1;
  }
}

const NAMED: Readonly<Record<string, string>> = { amp: '&', lt: '<', gt: '>', quot: '"', apos: '\'' };

/** The five predefined entities and character references; anything else stays as written, since there is no DTD to define it. */
export function decodeEntities(text: string): string {
  if (!text.includes('&')) return text;
  let result = '', at = 0;
  for (;;) {
    const amp = text.indexOf('&', at);
    if (amp === -1) return result + text.slice(at);
    const semicolon = text.indexOf(';', amp + 1);
    const entity = semicolon === -1 || semicolon - amp > 12 ? undefined : text.slice(amp + 1, semicolon);
    const decoded = entity === undefined ? undefined : NAMED[entity] ?? characterReference(entity);
    result += text.slice(at, amp) + (decoded ?? '&');
    at = decoded === undefined ? amp + 1 : semicolon + 1;
  }
}

function characterReference(entity: string): string | undefined {
  if (!entity.startsWith('#')) return undefined;
  const hex = entity[1] === 'x' || entity[1] === 'X';
  const digits = entity.slice(hex ? 2 : 1);
  const code = digits && [...digits].every(char => hex ? '0123456789abcdefABCDEF'.includes(char) : '0123456789'.includes(char)) ? parseInt(digits, hex ? 16 : 10) : NaN;
  return Number.isInteger(code) && code >= 0 && code <= 0x10ffff ? String.fromCodePoint(code) : undefined;
}
